name: FactionsPro
author: Tethered_
description: A Plugin For Easily Managing Factions
version: 1.3.11-3
main: FactionsPro\FactionMain
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
softdepend: ["PureChat", "AntiSpamPro"]
commands:
  f:
    description: use /f help for all parameters
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
